/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
      HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
      RouterLink: typeof import('vue-router')['RouterLink']
      RouterView: typeof import('vue-router')['RouterView']
      VanButton: typeof import('vant/es')['Button']
      VanCard: typeof import('vant/es')['Card']
      VanCell: typeof import('vant/es')['Cell']
      VanCellGroup: typeof import('vant/es')['CellGroup']
      VanCol: typeof import('vant/es')['Col']
      VanDivider: typeof import('vant/es')['Divider']
      VanGrid: typeof import('vant/es')['Grid']
      VanGridItem: typeof import('vant/es')['GridItem']
      VanIcon: typeof import('vant/es')['Icon']
      VanImage: typeof import('vant/es')['Image']
      VanNavBar: typeof import('vant/es')['NavBar']
      VanRow: typeof import('vant/es')['Row']
      VanSearch: typeof import('vant/es')['Search']
      VanSwipe: typeof import('vant/es')['Swipe']
      VanSwipeItem: typeof import('vant/es')['SwipeItem']
      VanTabbar: typeof import('vant/es')['Tabbar']
      VanTabbarItem: typeof import('vant/es')['TabbarItem']
      VanTag: typeof import('vant/es')['Tag']
      VanTreeSelect: typeof import('vant/es')['TreeSelect']
  }
}
