/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
      RouterLink: typeof import('vue-router')['RouterLink']
      RouterView: typeof import('vue-router')['RouterView']
      UserCardList: typeof import('./src/components/UserCardList.vue')['default']
      VanActionSheet: typeof import('vant/es')['ActionSheet']
      VanButton: typeof import('vant/es')['Button']
      VanCalendar: typeof import('vant/es')['Calendar']
      VanCard: typeof import('vant/es')['Card']
      VanCell: typeof import('vant/es')['Cell']
      VanCellGroup: typeof import('vant/es')['CellGroup']
      VanCol: typeof import('vant/es')['Col']
      VanCollapse: typeof import('vant/es')['Collapse']
      VanCollapseItem: typeof import('vant/es')['CollapseItem']
      VanDivider: typeof import('vant/es')['Divider']
      VanDropdownItem: typeof import('vant/es')['DropdownItem']
      VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
      VanEmpty: typeof import('vant/es')['Empty']
      VanField: typeof import('vant/es')['Field']
      VanForm: typeof import('vant/es')['Form']
      VanGrid: typeof import('vant/es')['Grid']
      VanGridItem: typeof import('vant/es')['GridItem']
      VanIcon: typeof import('vant/es')['Icon']
      VanImage: typeof import('vant/es')['Image']
      VanNavBar: typeof import('vant/es')['NavBar']
      VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
      VanOverlay: typeof import('vant/es')['Overlay']
      VanPasswordInput: typeof import('vant/es')['PasswordInput']
      VanPicker: typeof import('vant/es')['Picker']
      VanPopup: typeof import('vant/es')['Popup']
      VanRow: typeof import('vant/es')['Row']
      VanSearch: typeof import('vant/es')['Search']
      VanStepper: typeof import('vant/es')['Stepper']
      VanSwipe: typeof import('vant/es')['Swipe']
      VanSwipeItem: typeof import('vant/es')['SwipeItem']
      VanTabbar: typeof import('vant/es')['Tabbar']
      VanTabbarItem: typeof import('vant/es')['TabbarItem']
      VanTag: typeof import('vant/es')['Tag']
      VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
      VanTreeSelect: typeof import('vant/es')['TreeSelect']
      VanUploader: typeof import('vant/es')['Uploader']
  }
}
